Teashop2/Models/ShoppingCart.cs
namespace Teashop2.Models
{
    public class ShoppingCart
    {
        public List<OrderedProduct> Products { get; set; } = new List<OrderedProduct>();
        public void ClearCart()
        {
            Products.Clear();
        }
    }
}

Teashop2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DinkToPdf.Contracts;
using DinkToPdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Teashop2.Data;
using Teashop2.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Hosting;
using System.Threading;
using System.Text;

namespace Teashop2.Controllers
{
    public class OrderController : Controller
    {
        private readonly TeashopContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IServiceProvider _serviceProvider;
        private readonly IConverter _pdfConverter;

        public OrderController
            (
                TeashopContext context,
                UserManager<IdentityUser> userManager,
                IServiceProvider serviceProvider,
                IConverter pdfConverter
            )
        {
            _context = context;
            _userManager = userManager;
            _serviceProvider = serviceProvider;
            _pdfConverter = pdfConverter;
        }

        // GET: Order
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Index()
        {
            var teashopContext = _context.Orders.Include(o => o.Shipment).Where(o => o.Status != Status.SHIPPED);

            return View(await teashopContext.ToListAsync());
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserData()
        {
            IdentityUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound("User not found");
            }

            var orders = _context.Orders.Include(o => o.Shipment).Where(o => o.User.Id == user.Id).OrderByDescending(o => o.Date);

            return View(await orders.ToListAsync());
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Shipment)
                .Include(op => op.OrderedProducts)
                .ThenInclude(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            ViewData["Statuses"] = new SelectList(Enum.GetValues(typeof(Status)));

            return View(order);
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(int id, Status status)
        {
            Order order = _context.Orders.FirstOrDefault(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            order.Status = status;
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult GeneratePdf(int orderId)
        {
            var order = _context.Orders.Include(o => o.OrderedProducts).ThenInclude(o => o.Product).FirstOrDefault(o => o.Id == orderId);

            if (order == null)
            {
                return NotFound();
            }

            var html = GetHtmlContent(order);

            var pdf = _pdfConverter.Convert(new HtmlToPdfDocument()
            {
                GlobalSettings = {
                ColorMode = ColorMode.Color,
                Orientation = Orientation.Portrait,
                PaperSize = PaperKind.A4
            },
                Objects = {
                new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = html,
                    WebSettings = { DefaultEncoding = "utf-8" },
                }
            }
            });

            return File(pdf, "application/pdf", $"zamówienie{order.Date}.pdf");
        }

        private string GetHtmlContent(Order order)
        {
            string html = $@"
            <h1>Zamówienie nr {order.Id}</h1>
            <p>Data złożenia zamówienia: {order.Date}</p>
            <p>Adres wysyłki: {order.Address}</p>
            <p>Koszt całkowity: {order.TotalCost:c2}</p>
            <hr>
            <h2>Zamówione produkty</p>
            <table>
            <thead><tr><th>Produkt</th><th>Ilość</th><th>Cena jednostkowa [zł]</th><th>Wartość</th></tr></thead><tbody>
            ";

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append(html);
            foreach (OrderedProduct p in order.OrderedProducts)
            {
                stringBuilder.Append($"<tr><td>{p.Product.Name}</td><td>{p.Quantity}</td><td>{p.PricePerUnit:c2}</td><td>{p.Quantity * p.PricePerUnit:c2}</td></tr>");
            }
            stringBuilder.Append("</tbody></table>");

           
            return stringBuilder.ToString();
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Teashop2/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Teashop2.Areas.Identity.Data;
using Teashop2.Data;
using Teashop2.Models;
using Teashop2.ViewModels;

namespace Teashop2.Controllers
{
    [Authorize(Roles ="User")]
    public class ShoppingCartController : Controller
    {
        private readonly ShoppingCart _shoppingCart;
        private readonly TeashopContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ShoppingCartController(
            ShoppingCart shoppingCart, 
            TeashopContext context,
            UserManager<IdentityUser> userManager
        )
        {
            _shoppingCart = shoppingCart;
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            List<OrderedProduct> copy = new List<OrderedProduct>(_shoppingCart.Products);

            foreach (OrderedProduct item in copy)
            {
                Product product = _context.Products.FirstOrDefault(p => p.Id == item.Product.Id);
                //int quantityOnStock = _context.Products.FirstOrDefault(p => p.Id == item.Product.Id).QuantityOnStock;

                if (product.QuantityOnStock < item.Quantity)
                    item.Quantity = product.QuantityOnStock;
                if (!product.IsAvaliable || product.QuantityOnStock == 0)
                    _shoppingCart.Products.Remove(item);
            }

            return View(_shoppingCart.Products);
        }

        public IActionResult AddToCart(int productId)
        {
            OrderedProduct product = _shoppingCart.Products.FirstOrDefault(x => x.Product.Id == productId);

            if (product != null)
               product.Quantity += 1;
            else
            {
                Product actualProduct = _context.Products.FirstOrDefault(p => p.Id == productId);

                OrderedProduct productToAdd = new OrderedProduct {Product = actualProduct, Quantity = 1 };
                _shoppingCart.Products.Add(productToAdd);
            }

            //return RedirectToAction("Index");
            return RedirectToAction("Details", "Product", new { id = productId });
        }

        public IActionResult RemoveFromCart(int productId)
        {
            OrderedProduct product = _shoppingCart.Products.FirstOrDefault(x => x.ProductId == productId);

            if (product != null)
            {
                _shoppingCart.Products.Remove(product);
            }

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            _shoppingCart.ClearCart();

            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var viewModel = new CheckoutViewModel
            {
                Order = new Order(),
                Shipments = _context.Shipments.ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Checkout([Bind("PostalCode, City, Street, HouseNo, ShipmentId")]  Order order)
        {
            IdentityUser user = _userManager.GetUserAsync(User).Result;

            foreach (var item in _shoppingCart.Products)
            {
                item.PricePerUnit = item.Product.Price;
                item.ProductId = item.Product.Id;
                order.OrderedProducts.Add(item);
            }

            order.User = user;
            //order.UserId = user.Id;
            order.Shipment = _context.Shipments.FirstOrDefault(s => s.Id == order.ShipmentId);
            order.Status = Status.PAID;
            order.Date = DateTime.Now;
            order.TotalCost = _shoppingCart.Products.Sum(x => x.Quantity * x.Product.Price) + order.Shipment.Price;

            _context.Orders.Add(order);
            _context.UpdateProductsAfterCheckout(_shoppingCart.Products);
            _context.SaveChanges();

            _shoppingCart.ClearCart();

            return View("Success");
        }

    }
}

Teashop2/Views/ShoppingCart/Checkout.cshtml
@model Teashop2.ViewModels.CheckoutViewModel

<h1>Składanie zamówienia</h1>

<form asp-controller="ShoppingCart" asp-action="Checkout" method="post">
    <div class="form-group">
        <label for="PostalCode">Kod pocztowy</label>
        <input type="text" class="form-control" id="PostalCode" name="PostalCode" required>
    </div>
    <div class="form-group">
        <label for="City">Miasto</label>
        <input type="text" class="form-control" id="City" name="City" required>
    </div>
    <div class="form-group">
        <label for="Street">Ulica</label>
        <input type="text" class="form-control" id="Street" name="Street" required>
    </div>
    <div class="form-group">
        <label for="HouseNo">Numer domu</label>
        <input type="text" class="form-control" id="HouseNo" name="HouseNo" required>
    </div>
    <div class="form-group">
        <label for="ShipmentId">Sposób dostawy</label>
        <select class="form-control" id="ShipmentId" name="ShipmentId" required>
            <option value="">Wybierz sposób dostawy</option>
            @foreach (var shipment in Model.Shipments)
            {
                <option value="@shipment.Id">@shipment.Name - @shipment.Price zł (szacowany czas dostawy: @shipment.EstimatedTime)</option>
            }
        </select>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Złóż zamówienie</button>
</form>

Teashop2/Views/ShoppingCart/Index.cshtml
@model List<Teashop2.Models.OrderedProduct>

@{
    ViewData["Title"] = "Index";
}

<h1>Koszyk</h1>
<h4>
    Całkowity koszt produktów:  @($"{Model.Sum(p => p.Quantity * p.Product.Price):c2}")
</h4>
@*<button id="btn-clear" class="btn btn-danger">Wyczyść koszyk</button>*@
<a href="#" id="btn-clear" class="btn btn-danger">Wyczyść koszyk</a>



<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Produkt
            </th>
            <th>
                Ilość
            </th>
            <th>
                Cena jednostkowa
            </th>
            <th>
                Wartość
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (!string.IsNullOrEmpty(item.Product.ImagePath))
                    {
                        <img src="@Url.Content(item.Product.ImagePath)" class="img-thumbnail" style="max-width: 150px;" />
                    }
                    else
                    {
                        <img src="@Url.Content("/images/placeholder.jpg")" class="img-thumbnail" style="max-width: 150px;" />
                    }
                </td>
                <td class="product-name">
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@item.Product.Id">
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @($"{item.Product.Price:c2}")
                </td>
                <td>
                    @($"{item.Product.Price * item.Quantity:c2}") zł
                </td>
                <td>
                    @*<a asp-controller="ShoppingCart" asp-action="RemoveFromCart" asp-route-productId="@item.ProductId">Usuń</a>*@
                    <a href="#" class="btn-remove btn btn-danger" data-product-id="@item.ProductId"><i class="bi bi-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.Count > 0)
{
    <a asp-controller="ShoppingCart" asp-action="Checkout" class="btn btn-success">Złóż zamówienie</a>
}


@section scripts {
    <script>
        $(document).ready(function () {
            $(".btn-remove").click(function (e) {
                e.preventDefault();
                var productId = $(this).data("product-id");
                var productName = $(this).closest("tr").find(".product-name").text(); // Pobierz nazwę produktu z odpowiedniej kolumny
                $("#confirmDeleteModal .modal-body").html("Czy na pewno chcesz usunąć produkt: " + productName + "?");
                $("#confirmDeleteModal").modal("show");

                $("#btn-confirm-remove").click(function () {
                    window.location.href = '@Url.Action("RemoveFromCart", "ShoppingCart")' + '?productId=' + productId;
                });                
                $(".close-modal").click(function () {
                    $("#confirmDeleteModal").modal("hide");
                });
            });

            $("#btn-clear").click(function (e) {
                console.log("klyk");
                $("#confirmClearModal .modal-body").html("Czy na pewno chcesz wyczyścić koszyk? Operacja jest nieodwracalna!");
                $("#confirmClearModal").modal("show");

                $("#btn-confirm-clear").click(function () {
                    window.location.href = '@Url.Action("ClearCart", "ShoppingCart")';
                });
                $(".close-modal").click(function () {
                    $("#confirmClearModal").modal("hide");
                });
            });
        });
    </script>
}

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Potwierdzenie usuwania</h5>
                <button type="button" class="btn-close close-modal" data-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                Czy na pewno chcesz usunąć ten produkt z koszyka?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Anuluj</button>
                <button id="btn-confirm-remove" type="button" class="btn btn-danger">Usuń</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmClearModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Wyczyść koszyk</h5>
                <button type="button" class="btn-close close-modal" data-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                Czy na pewno chcesz wyczyścić koszyk? Operacja jest nieodwracalna!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Anuluj</button>
                <button id="btn-confirm-clear" type="button" class="btn btn-danger">Wyczyść</button>
            </div>
        </div>
    </div>
</div>

Teashop2/Views/ShoppingCart/Success.cshtml
@{
    ViewData["Title"] = "Potwierdzenie zamówienia";
}

<h1>@ViewData["Title"]</h1>
    <p>
        Zamówienie złożono pomyślnie. 
        <a asp-controller="Order" asp-action="UserData">Przejdź do listy wszystkich zamówień</a>
    </p>