Teashop2/Models/Order.cs
using Microsoft.AspNetCore.Identity;
using Teashop2.Areas.Identity.Data;

namespace Teashop2.Models
{
    public enum Status
    {
        PAID,
        COMPLETING,
        SHIPPED
    }

    public class Order
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public Status Status { get; set; }
        public float TotalCost { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string HouseNo { get; set; }
        public string Address { get => $"ul. {Street} {HouseNo}, {PostalCode} {City}";} 

        public IdentityUser User{ get; set; }
        public int ShipmentId { get; set; }
        public Shipment Shipment { get; set; }
        public ICollection<OrderedProduct> OrderedProducts { get; set; } = new List<OrderedProduct>();
    }
}

Teashop2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DinkToPdf.Contracts;
using DinkToPdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Teashop2.Data;
using Teashop2.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Hosting;
using System.Threading;
using System.Text;

namespace Teashop2.Controllers
{
    public class OrderController : Controller
    {
        private readonly TeashopContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IServiceProvider _serviceProvider;
        private readonly IConverter _pdfConverter;

        public OrderController
            (
                TeashopContext context,
                UserManager<IdentityUser> userManager,
                IServiceProvider serviceProvider,
                IConverter pdfConverter
            )
        {
            _context = context;
            _userManager = userManager;
            _serviceProvider = serviceProvider;
            _pdfConverter = pdfConverter;
        }

        // GET: Order
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Index()
        {
            var teashopContext = _context.Orders.Include(o => o.Shipment).Where(o => o.Status != Status.SHIPPED);

            return View(await teashopContext.ToListAsync());
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserData()
        {
            IdentityUser user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound("User not found");
            }

            var orders = _context.Orders.Include(o => o.Shipment).Where(o => o.User.Id == user.Id).OrderByDescending(o => o.Date);

            return View(await orders.ToListAsync());
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Shipment)
                .Include(op => op.OrderedProducts)
                .ThenInclude(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            ViewData["Statuses"] = new SelectList(Enum.GetValues(typeof(Status)));

            return View(order);
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(int id, Status status)
        {
            Order order = _context.Orders.FirstOrDefault(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            order.Status = status;
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult GeneratePdf(int orderId)
        {
            var order = _context.Orders.Include(o => o.OrderedProducts).ThenInclude(o => o.Product).FirstOrDefault(o => o.Id == orderId);

            if (order == null)
            {
                return NotFound();
            }

            var html = GetHtmlContent(order);

            var pdf = _pdfConverter.Convert(new HtmlToPdfDocument()
            {
                GlobalSettings = {
                ColorMode = ColorMode.Color,
                Orientation = Orientation.Portrait,
                PaperSize = PaperKind.A4
            },
                Objects = {
                new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = html,
                    WebSettings = { DefaultEncoding = "utf-8" },
                }
            }
            });

            return File(pdf, "application/pdf", $"zamówienie{order.Date}.pdf");
        }

        private string GetHtmlContent(Order order)
        {
            string html = $@"
            <h1>Zamówienie nr {order.Id}</h1>
            <p>Data złożenia zamówienia: {order.Date}</p>
            <p>Adres wysyłki: {order.Address}</p>
            <p>Koszt całkowity: {order.TotalCost:c2}</p>
            <hr>
            <h2>Zamówione produkty</p>
            <table>
            <thead><tr><th>Produkt</th><th>Ilość</th><th>Cena jednostkowa [zł]</th><th>Wartość</th></tr></thead><tbody>
            ";

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append(html);
            foreach (OrderedProduct p in order.OrderedProducts)
            {
                stringBuilder.Append($"<tr><td>{p.Product.Name}</td><td>{p.Quantity}</td><td>{p.PricePerUnit:c2}</td><td>{p.Quantity * p.PricePerUnit:c2}</td></tr>");
            }
            stringBuilder.Append("</tbody></table>");

           
            return stringBuilder.ToString();
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Teashop2/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;
using Org.BouncyCastle.Asn1.Crmf;
using Teashop2.Data;
using Teashop2.Models;
using Teashop2.ViewModel;

namespace Teashop2.Controllers
{
    public class ProductController : Controller
    {
        private readonly TeashopContext _context;

        public ProductController(TeashopContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index(
            string sortOrder, 
            string currentFilter,
            string searchString,
            int? pageNumber,
            int? categoryFilter
            )
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["categoryFilter"] = categoryFilter;
            ViewBag.Categories = await _context.Categories.ToListAsync();

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;


            var products = from p in _context.Products
                           select p;

            if (categoryFilter.HasValue)
            {
                products = products.Where(p => p.Categories.Any(c => c.Id == categoryFilter));
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.Name.ToUpper().Contains(searchString.ToUpper())
                                       || p.Description.ToUpper().Contains(searchString.ToUpper()))
                                    .Include(p => p.Categories);

            }

            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(p => p.IsAvaliable).ThenByDescending(p => p.Name);
                    break;
                case "Price":
                    products = products.OrderByDescending(p => p.IsAvaliable).ThenBy(p => p.Price);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(p => p.IsAvaliable).ThenByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderByDescending(p => p.IsAvaliable).ThenBy(p => p.Name);
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Product>.CreateAsync(products.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Categories)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            var viewModel = new AddProductViewModel
            {
                Product = new Product(),
                Categories = new List<CategoryViewModel>()
            };

            foreach (Category cat in _context.Categories)
                viewModel.Categories.Add(
                        new CategoryViewModel
                        {
                            Id = cat.Id,
                            Name = cat.Name
                        }
                    );

            return View(viewModel);
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Product, Categories")] AddProductViewModel model, IFormFile imageFile)
        {
            try
            {
                var selectedCategories = model.Categories.Where(cat => cat.IsSelected).Select(cat => cat.Id);

                if (selectedCategories.Any())
                {
                    var product = new Product
                    {
                        Name = model.Product.Name,
                        Description = model.Product.Description,
                        Price = model.Product.Price,
                        QuantityOnStock = model.Product.QuantityOnStock,
                        IsAvaliable = model.Product.IsAvaliable,
                        Categories = _context.Categories.Where(cat => selectedCategories.Contains(cat.Id)).ToList(),
                        ImagePath = await SaveImage(imageFile)
                    };

                    _context.Add(product);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, " +
                    "see your system administrator.");
            }
            return View(model);
        }

        // GET: Products/Edit/5
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                                            .Include(p => p.Categories)
                                            .AsNoTracking()
                                            .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            var viewModel = new AddProductViewModel
            {
                Product = product,
                Categories = new List<CategoryViewModel>(),
                PreviousImagePath = product.ImagePath
            };

            foreach (Category cat in _context.Categories)
            {
                var categoryViewModel = new CategoryViewModel
                {
                    Id = cat.Id,
                    Name = cat.Name
                };

                if (product.Categories.Any(selectedCat => selectedCat.Id == cat.Id))
                {
                    categoryViewModel.IsSelected = true;
                }

                viewModel.Categories.Add(categoryViewModel);
            }

            return View(viewModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Product, Categories, PreviousImagePath")] AddProductViewModel model, IFormFile? imageFile)
        {
            try
            {
                if (id != model.Product.Id)
                {
                    return NotFound();
                }

                var selectedCategories = model.Categories.Where(cat => cat.IsSelected).Select(cat => cat.Id);

                if (selectedCategories.Any())
                {
                    Product product = _context.Products
                                    .Include(p => p.Categories)
                                    .FirstOrDefault(p => p.Id == id);

                    product.Name = model.Product.Name;
                    product.Description = model.Product.Description;
                    product.Price = model.Product.Price;
                    product.QuantityOnStock = model.Product.QuantityOnStock;
                    product.IsAvaliable = model.Product.IsAvaliable;

                    if (imageFile != null)
                    {
                        product.ImagePath = await SaveImage(imageFile);
                    }
                    else if (!string.IsNullOrEmpty(model.PreviousImagePath))
                    {
                        product.ImagePath = model.PreviousImagePath;
                    }

                    var selectedCategoryIds = model.Categories.Where(cat => cat.IsSelected).Select(cat => cat.Id).ToList();
                    var categories = _context.Categories.Where(cat => selectedCategoryIds.Contains(cat.Id)).ToList();

                    product.Categories.Clear();
                    product.Categories.AddRange(categories);
                    _context.Products.Update(product);
                    _context.SaveChanges();

                    return RedirectToAction(nameof(Index));

                }

                else
                    return View(model);
            }

            catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(model.Product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }            
        }

        private bool ProductExists(int id)
        {
          return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }

Teashop2/Views/Order/Details.cshtml
@using Teashop2.Extensions
@inject IServiceProvider ServiceProvider
@model Teashop2.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-10 col-xl-8">
            <div class="card" style="border-radius: 10px;">
                <div class="card-header px-4 py-5">
                    <h5 class="mb-0">Szczegóły zamówienia</h5>
                </div>
                <div class="card-body p-4">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <p class="lead fw-normal mb-0">Produkty</p>
                        <p class="small text-muted mb-0">Nr zamówienia : @Model.Id</p>
                    </div>
                    <div class='card shadow-0 border mb-4'>
                        <div class='card-body'>
                            @foreach (var item in Model.OrderedProducts)
                            {
                                <div class='row'>

                                <div class='col-md-4 text-center d-flex justify-content-center align-items-center'>
                                        <a asp-controller="Product" asp-action="Details" asp-route-id="@item.Product.Id" class='text-muted mb-0'>@item.Product.Name</a>
                                </div>
                                <div class='col-md-4 text-center d-flex justify-content-center align-items-center'>
                                    <p class='text-muted mb-0 small'>Ilość: @item.Quantity</p>
                                </div>
                                <div class='col-md-4 text-center d-flex justify-content-center align-items-center'>
                                        <p class='text-muted mb-0 small'>@($"{item.PricePerUnit:c2}")/szt.</p>
                                </div>
                            </div>
                            }
                        </div>
                    </div>

                    <div class="d-flex justify-content-between pt-2">
                        <p class="fw-bold mb-0">Szczegóły:</p>
                        <p class="text-muted mb-0"><span class="fw-bold me-4">Łącznie:</span> @($"{Model.TotalCost - Model.Shipment.Price:c2}") zł</p>
                    </div>

                    <div class="d-flex justify-content-between pt-2">
                        <p class="text-muted mb-0">Dane adresowe:</p>
                    </div>

                    <div class="d-flex justify-content-between">
                        <p class="text-muted mb-0">@Model.Address</p>
                    </div>

                    <div class="d-flex justify-content-between mb-5">
                        <p class="text-muted mb-0">Dostawa : @Model.Shipment.Name</p>
                        <p class="text-muted mb-0"><span class="fw-bold me-4">Koszt wysyłki: </span>@($"{Model.Shipment.Price:c2}") zł</p>
                    </div>
                </div>
                <div class="card-footer border-1 px-4 py-5"
                     style="border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                    <h5 class="d-flex align-items-center justify-content-end text-uppercase mb-0">Całkowity koszt: @($"{Model.TotalCost:c2}")</h5>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex justify-content-center align-items-center h-100">
    @if (User.IsInPolicy("writepolicy", ServiceProvider))
    {
        <label asp-for="Status" class="control-label">Status:&nbsp;</label>
        <select id="statusDropdown" class="form-control w-25" asp-for="Status" asp-items="ViewBag.Statuses"></select>

        <div class="form-group">
            <button id="changeStatusButton" class="btn btn-success">Zmień status</button>
        </div>
    }
</div>
<br />
<p class="text-center">
    @if (User.IsInPolicy("writepolicy", ServiceProvider))
    {
        <a asp-action="Index" asp-controller="Order">Powrót</a>
    }
    else
    {
        <a asp-action="UserData" asp-controller="Order">Powrót</a>
    }
</p>

@section scripts
{
        <script>
            document.getElementById("changeStatusButton").addEventListener("click", function () {
                var selectedStatus = document.getElementById("statusDropdown").value;
                var url = '@Url.Action("Edit", new { id = Model.Id, status = "STATUS" })'.replace("STATUS", selectedStatus);
                window.location.href = url;
            });
        </script>
}

Teashop2/Views/Order/Index.cshtml
@model IEnumerable<Teashop2.Models.Order>

@{
    ViewData["Title"] = "Zamówienia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Oczekujące zamówienia</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th>
                Status
            </th>
            <th>
                Koszt
            </th>
            <th>
                Dostawa
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TotalCost)*@
                @item.TotalCost.ToString("c2")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Shipment.Name)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Szczegóły</a>
            </td>
        </tr>
}
    </tbody>
</table>

Teashop2/Views/Order/UserData.cshtml
@model IEnumerable<Teashop2.Models.Order>

@{
    ViewData["Title"] = "Zamówienia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Historia zamówień</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th>
                Status
            </th>
            <th>
                Koszt
            </th>
            <th>
                Dostawa
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @item.TotalCost.ToString("c2")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shipment.Name)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Szczegóły</a><br>
                    <a asp-controller="Order" asp-action="GeneratePdf" asp-route-orderId="@item.Id" target="_blank" class="btn btn-secondary">Generuj PDF</a>
                </td>
            </tr>
        }
    </tbody>
</table>